name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build & Unit Test
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '10.0.x' ]

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Debug --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
